[project]
name = "flights-data-engineering-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awswrangler>=3.16.0",
    "boto3>=1.42.87",
    "pandas>=3.0.2",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.49",
]
